fixed the pending issues: ?

diff --git a/scripts/password b/scripts/password
--- a/scripts/password
+++ b/scripts/password
@@ -71,9 +71,183 @@ function f_password {
   echo "account required pam_tally2.so" >> "$COMMONACCOUNT"
   fi
 
-  cp "./misc/passwords.list" "/usr/share/dict/passwords"
-  grep -v '^$' /usr/share/dict/passwords | strings > /usr/share/dict/passwords_text
-  update-cracklib
+########### Limit reuse of password on ubuntu 22 #######
+if grep jammy /etc/os-release; then
+         # Remediation is applicable only in certain platforms
+         if dpkg-query --show --showformat='${db:Status-Status}\n' 'libpam-runtime' 2>/dev/null | grep -q installed; then
+
+         var_password_pam_unix_remember='5'
+
+         if [ -e "/etc/pam.d/common-password" ] ; then
+             valueRegex="$var_password_pam_unix_remember" defaultValue="$var_password_pam_unix_remember"
+             # non-empty values need to be preceded by an equals sign
+             [ -n "${valueRegex}" ] && valueRegex="=${valueRegex}"
+             # add an equals sign to non-empty values
+             [ -n "${defaultValue}" ] && defaultValue="=${defaultValue}"
+
+             # fix 'type' if it's wrong
+             if grep -q -P "^\\s*(?"'!'"password\\s)[[:alnum:]]+\\s+[[:alnum:]]+\\s+pam_unix.so" < "/etc/pam.d/common-password" ; then
+                 sed --follow-symlinks -i -E -e "s/^(\\s*)[[:alnum:]]+(\\s+[[:alnum:]]+\\s+pam_unix.so)/\\1password\\2/" "/etc/pam.d/common-password"
+             fi
+
+             # fix 'control' if it's wrong
+             if grep -q -P "^\\s*password\\s+(?"'!'"\[success=[[:alnum:]].*\])[[:alnum:]]+\\s+pam_unix.so" < "/etc/pam.d/common-password" ; then
+                 sed --follow-symlinks -i -E -e "s/^(\\s*password\\s+)[[:alnum:]]+(\\s+pam_unix.so)/\\1\[success=[[:alnum:]].*\]\\2/" "/etc/pam.d/common-password"
+             fi
+
+             # fix the value for 'option' if one exists but does not match 'valueRegex'
+             if grep -q -P "^\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so(\\s.+)?\\s+remember(?"'!'"${valueRegex}(\\s|\$))" < "/etc/pam.d/common-password" ; then
+                 sed --follow-symlinks -i -E -e "s/^(\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so(\\s.+)?\\s)remember=[^[:space:]]*/\\1remember${defaultValue}/" "/etc/pam.d/common-password"
+
+             # add 'option=default' if option is not set
+             elif grep -q -E "^\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so" < "/etc/pam.d/common-password" &&
+                     grep    -E "^\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so" < "/etc/pam.d/common-password" | grep -q -E -v "\\sremember(=|\\s|\$)" ; then
+
+                 sed --follow-symlinks -i -E -e "s/^(\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so[^\\n]*)/\\1 remember${defaultValue}/" "/etc/pam.d/common-password"
+             # add a new entry if none exists
+             elif ! grep -q -P "^\\s*password\\s+\[success=[[:alnum:]].*\]\\s+pam_unix.so(\\s.+)?\\s+remember${valueRegex}(\\s|\$)" < "/etc/pam.d/common-password" ; then
+                 echo "password \[success=[[:alnum:]].*\] pam_unix.so remember${defaultValue}" >> "/etc/pam.d/common-password"
+             fi
+         else
+             echo "/etc/pam.d/common-password doesn't exist" >&2
+         fi
+
+         else
+             >&2 echo 'Remediation is not applicable, nothing was done'
+         fi
+    fi
+
+### Lock accounts after failed password attempts on ubuntu 22  #####
+
+if grep jammy /etc/os-release; then
+    # Remediation is applicable only in certain platforms
+    if dpkg-query --show --showformat='${db:Status-Status}\n' 'libpam-runtime' 2>/dev/null | grep -q installed; then
+
+        var_accounts_passwords_pam_faillock_deny='4'
+
+        if [ -f /usr/bin/authselect ]; then
+    if ! authselect check; then
+            echo "
+            authselect integrity check failed. Remediation aborted!
+            This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact.
+            It is not recommended to manually edit the PAM files when authselect tool is available.
+            In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
+            exit 1
+            fi
+            authselect enable-feature with-faillock
+
+            authselect apply-changes -b
+            else
+
+            pam_file="/etc/pam.d/common-auth"
+            if ! grep -qE '^\s*auth\s+required\s+pam_faillock\.so\s+preauth.*$' "$pam_file" ; then
+                sed -i --follow-symlinks '/^auth.*pam_unix\.so.*/i auth        required      pam_faillock.so preauth' "$pam_file"
+            fi
+            if ! grep -qE '^\s*auth\s+\[default=die\]\s+pam_faillock\.so\s+authfail.*$' "$pam_file" ; then
+                num_lines=$(sed -n 's/^auth.*success=\([0-9]\).*pam_unix\.so.*/\1/p' "$pam_file")
+                if [ ! -z "$num_lines" ]; then
+                    echo "$num_lines"
+                    pattern=""
+                    for ((i=1; i <= num_lines; i++)); do
+                        pattern="${pattern}n;"
+                    done;
+                    sed -i --follow-symlinks '/^auth.*pam_unix\.so.*/{'$pattern'a auth        [default=die]      pam_faillock.so authfail
+             }' "$pam_file"
+                else
+                    sed -i --follow-symlinks '/^auth.*pam_unix\.so.*/a auth        [default=die]      pam_faillock.so authfail' "$pam_file"
+                fi
+            fi
+            if ! grep -qE '^\s*auth\s+sufficient\s+pam_faillock\.so\s+authsucc.*$' "$pam_file" ; then
+                sed -i --follow-symlinks '/^auth.*pam_faillock\.so.*authfail.*/a auth        sufficient      pam_faillock.so authsucc' "$pam_file"
+            fi
+
+            pam_file="/etc/pam.d/common-account"
+            if ! grep -qE '^\s*account\s+required\s+pam_faillock\.so.*$' "$pam_file" ; then
+                echo 'account   required     pam_faillock.so' >> "$pam_file"
+            fi
+
+            fi
+
+            AUTH_FILES=("/etc/pam.d/common-auth" "/etc/pam.d/password-auth")
+
+            FAILLOCK_CONF="/etc/security/faillock.conf"
+            if [ -f $FAILLOCK_CONF ]; then
+                regex="^\s*deny\s*="
+                line="deny = $var_accounts_passwords_pam_faillock_deny"
+                if ! grep -q $regex $FAILLOCK_CONF; then
+                    echo $line >> $FAILLOCK_CONF
+                else
+                    sed -i --follow-symlinks 's|^\s*\(deny\s*=\s*\)\(\S\+\)|\1'"$var_accounts_passwords_pam_faillock_deny"'|g' $FAILLOCK_CONF
+                fi
+                for pam_file in "${AUTH_FILES[@]}"
+                do
+                    if [ -e "$pam_file" ] ; then
+                        PAM_FILE_PATH="$pam_file"
+                        if [ -f /usr/bin/authselect ]; then
+
+                            if ! authselect check; then
+                            echo "
+                            authselect integrity check failed. Remediation aborted!
+                            This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact.
+                            It is not recommended to manually edit the PAM files when authselect tool is available.
+                            In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
+                            exit 1
+                            fi
+
+                            CURRENT_PROFILE=$(authselect current -r | awk '{ print $1 }')
+                            # If not already in use, a custom profile is created preserving the enabled features.
+                            if [[ ! $CURRENT_PROFILE == custom/* ]]; then
+                                ENABLED_FEATURES=$(authselect current | tail -n+3 | awk '{ print $2 }')
+                                authselect create-profile hardening -b $CURRENT_PROFILE
+                                CURRENT_PROFILE="custom/hardening"
+
+                                authselect apply-changes -b --backup=before-hardening-custom-profile
+                                authselect select $CURRENT_PROFILE
+                                for feature in $ENABLED_FEATURES; do
+                                    authselect enable-feature $feature;
+                                done
+
+                                authselect apply-changes -b --backup=after-hardening-custom-profile
+                            fi
+                            PAM_FILE_NAME=$(basename "$pam_file")
+                            PAM_FILE_PATH="/etc/authselect/$CURRENT_PROFILE/$PAM_FILE_NAME"
+
+                            authselect apply-changes -b
+                        fi
+
+                    if grep -qP '^\s*auth\s.*\bpam_faillock.so\s.*\bdeny\b' "$PAM_FILE_PATH"; then
+                        sed -i -E --follow-symlinks 's/(.*auth.*pam_faillock.so.*)\bdeny\b=?[[:alnum:]]*(.*)/\1\2/g' "$PAM_FILE_PATH"
+                    fi
+                        if [ -f /usr/bin/authselect ]; then
+
+                            authselect apply-changes -b
+                        fi
+                    else
+                        echo "$pam_file was not found" >&2
+                    fi
+                done
+            else
+                for pam_file in "${AUTH_FILES[@]}"
+                do
+                    if ! grep -qE '^\s*auth.*pam_faillock\.so (preauth|authfail).*deny' "$pam_file"; then
+                        sed -i --follow-symlinks '/^auth.*required.*pam_faillock\.so.*preauth.*silent.*/ s/$/ deny='"$var_accounts_passwords_pam_faillock_deny"'/' "$pam_file"
+                        sed -i --follow-symlinks '/^auth.*required.*pam_faillock\.so.*authfail.*/ s/$/ deny='"$var_accounts_passwords_pam_faillock_deny"'/' "$pam_file"
+                    else
+                        sed -i --follow-symlinks 's/\(^auth.*required.*pam_faillock\.so.*preauth.*silent.*\)\('"deny"'=\)[0-9]\+\(.*\)/\1\2'"$var_accounts_passwords_pam_faillock_deny"'\3/' "$pam_file"
+                        sed -i --follow-symlinks 's/\(^auth.*required.*pam_faillock\.so.*authfail.*\)\('"deny"'=\)[0-9]\+\(.*\)/\1\2'"$var_accounts_passwords_pam_faillock_deny"'\3/' "$pam_file"
+                    fi
+                done
+            fi
+
+         else
+                >&2 echo 'Remediation is not applicable, nothing was done'
+            fi
+
+        fi
+
+cp "./misc/passwords.list" "/usr/share/dict/passwords"
+grep -v '^$' /usr/share/dict/passwords | strings > /usr/share/dict/passwords_text
+update-cracklib
 
   ((SCRIPT_COUNT++))
 }
